use_frameworks!

target 'CCCLib_Example' do
  pod 'CCCLib', :path => '../'

  target 'CCCLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
