use_frameworks!

target 'BBBLib_Example' do
  pod 'BBBLib', :path => '../'

  target 'BBBLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
