use_frameworks!

target 'AAALib_Example' do
  pod 'AAALib', :path => '../'

  target 'AAALib_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
